[config]
version_check = false
caching = true


[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/hyprland-colors.conf"
post_hook = "hyprctl reload"

[templates.foot]
input_path = "./templates/foot-colors.ini"
output_path = "~/.config/foot/foot-colors.ini"

# [templates.starship]
# input_path = "./templates/starship-colors.toml"
# output_path = "~/.config/starship.toml"

[templates.ghostty]
input_path = './templates/ghostty-colors'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.tmux]
input_path = './templates/tmux-colors.conf'
output_path = '~/.config/tmux/colors.conf'
post_hook = 'tmux source-file ~/.config/tmux/colors.conf'
